name: Code Review Workflow

on:
  push:
    branches:
      - Assignment02_GithubActions
  pull_request:
    branches:
      - Assignment02_GithubActions
  workflow_dispatch:

jobs:
  code-review:
    name: Code Review (Lint + CodeQL)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

       #name: Run ESLint
        #run: npx eslint .

      # ✅ CodeQL Steps
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
